# Generated by Django 6.0.1 on 2026-01-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_description_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='core.department'),
        ),
    ]
