# Generated by Django 6.0.1 on 2026-01-27 11:42

from django.db import migrations, models


def migrate_hours_to_ltp(apps, schema_editor):
    """Copy hours_per_week values to lecture_hours for existing subjects"""
    Subject = apps.get_model('core', 'Subject')
    for subject in Subject.objects.all():
        subject.lecture_hours = subject.hours_per_week
        subject.save()


def reverse_ltp_to_hours(apps, schema_editor):
    """Reverse migration: copy lecture_hours back to hours_per_week"""
    Subject = apps.get_model('core', 'Subject')
    for subject in Subject.objects.all():
        subject.hours_per_week = subject.lecture_hours
        subject.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_timeslot_fields'),
    ]

    operations = [
        # Step 1: Add new L-T-P fields with defaults
        migrations.AddField(
            model_name='subject',
            name='lecture_hours',
            field=models.IntegerField(default=3, help_text='Lecture hours per week (L)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_hours',
            field=models.IntegerField(default=0, help_text='Practical/Lab hours per week (P)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tutorial_hours',
            field=models.IntegerField(default=0, help_text='Tutorial hours per week (T)'),
        ),
        # Step 2: Migrate existing hours_per_week data to lecture_hours
        migrations.RunPython(migrate_hours_to_ltp, reverse_ltp_to_hours),
        # Step 3: Remove the old hours_per_week column
        migrations.RemoveField(
            model_name='subject',
            name='hours_per_week',
        ),
    ]
