# Generated by Django 6.0.1 on 2026-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_ltp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('MORNING', 'Morning Period'), ('AFTERNOON', 'Afternoon Period'), ('LUNCH', 'Lunch Break'), ('RECESS', 'Recess Break')], default='MORNING', max_length=10),
        ),
    ]
