# Generated by Django 4.2.27 on 2026-01-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_timeslot_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_code',
            field=models.CharField(blank=True, help_text='Abbreviation (e.g., CD for Compiler Design)', max_length=10, null=True),
        ),
    ]
