# Generated by Django 4.2.27 on 2026-03-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('ELECTIVE', 'Elective'), ('REMEDIAL', 'Remedial'), ('MINOR', 'Minor'), ('HONOUR', 'Honour')], max_length=10),
        ),
    ]
