# Generated by Django 4.2.27 on 2026-03-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_remedial_minor_honour_subject_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('ELECTIVE', 'Elective'), ('RMH', 'Remedial/Minor/Honour')], max_length=10),
        ),
    ]
