# Generated by Django 4.2.27 on 2026-03-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_consolidate_rmh_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_remedial',
            field=models.BooleanField(default=False, help_text='Whether this is a Remedial/Minor/Honour slot'),
        ),
    ]
