# Generated by Django 4.2.27 on 2026-03-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_timetableentry_is_remedial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='max_workload_hours',
            field=models.IntegerField(blank=True, help_text='Custom maximum workload (overrides designation default)', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='min_workload_hours',
            field=models.IntegerField(blank=True, help_text='Custom minimum workload (overrides designation default)', null=True),
        ),
    ]
